// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantMonitoringSystem.BlazorWeb.Data;

#nullable disable

namespace PlantMonitoringSystem.BlazorWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlantMonitoringSystem.BlazorWeb.Data.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpdatePeriod")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("PlantMonitoringSystem.BlazorWeb.Data.SensorRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Humidity")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Light")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Moisture")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("PlantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Temperature")
                        .HasColumnType("tinyint");

                    b.Property<int>("UpdateTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("SensorRecords");
                });

            modelBuilder.Entity("PlantMonitoringSystem.BlazorWeb.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlantMonitoringSystem.BlazorWeb.Data.Plant", b =>
                {
                    b.HasOne("PlantMonitoringSystem.BlazorWeb.Data.User", "User")
                        .WithMany("Plants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantMonitoringSystem.BlazorWeb.Data.SensorRecord", b =>
                {
                    b.HasOne("PlantMonitoringSystem.BlazorWeb.Data.Plant", null)
                        .WithMany("Records")
                        .HasForeignKey("PlantId");
                });

            modelBuilder.Entity("PlantMonitoringSystem.BlazorWeb.Data.Plant", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("PlantMonitoringSystem.BlazorWeb.Data.User", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
